/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/dice.glb 
*/

import { useLayoutEffect, useRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import PropTypes from 'prop-types';

export function Model(props) {
  const group = useRef()
  const {play} = props;
  const { nodes, materials, animations } = useGLTF('../../public/dice.glb')
  const { actions, names } = useAnimations(animations, group);

  useLayoutEffect(() => {
    if (play) {
      names.forEach((animation) => {
        actions?.[animation]?.play();
      });
      actions.CubeAction.paused = false;
    } else {
      actions.CubeAction.paused = true;
      names.forEach((animation) => {
        // actions.CubeAction.stop();
        console.log(actions?.[animation]?.paused);
        // console.log("oi")
      });
    }
  }, [actions, names, play]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

Model.propTypes = {
  play: PropTypes.bool
}

useGLTF.preload('../../public/dice.glb')
